/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team13.server;


public class App {

   public static void main(String[] args) {
    App a = new App();

//    Game game = new RiscGame(2);
//    Server server = new Server(12345, game);
//    server.connectToClients();
  }
}
