/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team13.client;

import edu.duke.ece651.team13.shared.*;

import java.io.IOException;
import java.net.Socket;


public class App {
  public String getMessage() {
    return "Hello from the client for "+ MyName.getName();
  }
  public static void main(String[] args) {
    App a = new App();
    System.out.println(a.getMessage());

    // display a basic V1 map and exit
    V1Map map = new V1Map(100);
    BoardTextView view = new BoardTextView(map);
    System.out.println(view.display());

    // identifies which player and ask for action
    Player player = new HumanPlayer("Green", new Socket());
//    Client client = new Client("", 12345, player);
    try {
      player.placeUnits();
      player.playOneTurn();
    } catch (IOException e) {
      e.printStackTrace();
    }

  }
}
