/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team13.client;

import edu.duke.ece651.team13.shared.MyName;
import edu.duke.ece651.team13.shared.V1Map;


public class App {
  public String getMessage() {
    return "Hello from the client for "+ MyName.getName();
  }
  public static void main(String[] args) {
    App a = new App();
    System.out.println(a.getMessage());

    // display a basic V1 map and exit
    V1Map map = new V1Map(1);
    int initialUnit = map.getInitialUnit();
    System.out.println(initialUnit + " units in Territory1 (next to: Territory2)");
    System.out.println(initialUnit + " units in Territory2 (next to: Territory2)");
  }
}
