import React from "react";
import TerritoryView from "./TerritoryView";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Container from "react-bootstrap/Container";

const Map3Players = (props) => {
  const { territories } = props;
  const getTerritory = (name) => {
    return territories.find((territory) => territory.name === name);
  };

  return (
    <Container>
      <Row>
        <Col></Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Labrador"
            territory={getTerritory("Labrador")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Bulldog"
            territory={getTerritory("Bulldog")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col></Col>
      </Row>
      <Row>
        <Col></Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Rottweiler"
            territory={getTerritory("Rottweiler")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Dachshund"
            territory={getTerritory("Dachshund")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Beagle"
            territory={getTerritory("Beagle")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col></Col>
      </Row>
      <Row>
        <Col>
          <TerritoryView
            key="Boxer"
            territory={getTerritory("Boxer")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Spaniel"
            territory={getTerritory("Spaniel")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Poodle"
            territory={getTerritory("Poodle")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Pug"
            territory={getTerritory("Pug")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Mastiff"
            territory={getTerritory("Mastiff")}
            handleSource={props.handleSource}
          />
        </Col>
      </Row>
      <Row>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Brittany"
            territory={getTerritory("Brittany")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Havanese"
            territory={getTerritory("Havanese")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Vizsla"
            territory={getTerritory("Vizsla")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Chihuahua"
            territory={getTerritory("Chihuahua")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
      </Row>
      <Row>
        <Col>
          <TerritoryView
            key="Akita"
            territory={getTerritory("Akita")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Sheepdog"
            territory={getTerritory("Sheepdog")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col></Col>
        <Col></Col>
        <Col></Col>
        <Col>
          <TerritoryView
            key="Maltese"
            territory={getTerritory("Maltese")}
            handleSource={props.handleSource}
          />
        </Col>
        <Col>
          <TerritoryView
            key="Collie"
            territory={getTerritory("Collie")}
            handleSource={props.handleSource}
          />
        </Col>
      </Row>
    </Container>
  );
};

export default Map3Players;
